environment:
  npm_token:
    secure: CF0+NkSX0D4jrSH20ybWD6TXIiYK0X19r02p1u0NqZORVoCBVhmOCRVjc93Bd4DW

before_build:
  - npm install

build_script:
  - echo publish package
  - npm run ci-publish || true